# Generated by Django 2.0.5 on 2018-05-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180514_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='admin@myplanet.com', max_length=128),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Admin', max_length=255),
        ),
    ]
