# Generated by Django 2.0.5 on 2018-05-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20180515_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
